language: cpp
sudo: required
dist: trusty
compiler:
- g++-5
os:
- linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-5
      - g++-5
      - libsqlite3-dev
      - libboost-all-dev
      - libcurl4-openssl-dev
      - libgps-dev
      - libncurses5-dev
notifications:
  email: false
before_install:
- sudo apt update -y
- cd ~
- git clone git://git.drogon.net/wiringPi
- cd wiringPi/
- git pull origin
- ./build
install: export CXX="g++-5"
script:
- cd $TRAVIS_BUILD_DIR/NavigationSystem
- make ASPire
after_success:
- ./sr
branches:
  only:
  - master
