language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux
before_install:
- sudo apt update -y
- sudo apt install --only-upgrade g++
- sudo apt install libsqlite3-dev -y
- sudo apt install libboost-all-dev -y
- sudo apt install libcurl4-openssl-dev -y
- sudo apt install libgps-dev -y
- sudo apt install libncurses5-dev libncursesw5-dev
- cd ~
- git clone git://git.drogon.net/wiringPi
- cd wiringPi/
- git pull origin
- ./build
script:
- cd $TRAVIS_BUILD_DIR/NavigationSystem
- make ASPire
after_success:
- ./sr
branches:
  only:
  - master
