language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-4.9
      - g++-4.9
      - libsqlite3-dev
      - libboost-all-dev
      - libcurl4-openssl-dev
      - libgps-dev
      - libncurses5-dev

before_install:
- sudo apt update -y
- cd ~
- git clone git://git.drogon.net/wiringPi
- cd wiringPi/
- git pull origin
- ./build
script:
- cd $TRAVIS_BUILD_DIR/NavigationSystem
- make ASPire
after_success:
- ./sr
branches:
  only:
  - master
